"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class AppCleanInfo(object):
    __slots__ = ["cleanTimeSecond", "cleanArea", "cleanTimeTotalSecond", "cleanAreaTotal", "cleanCountTotal", "esimateArea"]

    __typenames__ = ["int32_t", "float", "int32_t", "float", "int32_t", "float"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.cleanTimeSecond = 0
        self.cleanArea = 0.0
        self.cleanTimeTotalSecond = 0
        self.cleanAreaTotal = 0.0
        self.cleanCountTotal = 0
        self.esimateArea = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(AppCleanInfo._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ififif", self.cleanTimeSecond, self.cleanArea, self.cleanTimeTotalSecond, self.cleanAreaTotal, self.cleanCountTotal, self.esimateArea))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != AppCleanInfo._get_packed_fingerprint():
            raise ValueError("Decode error")
        return AppCleanInfo._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = AppCleanInfo()
        self.cleanTimeSecond, self.cleanArea, self.cleanTimeTotalSecond, self.cleanAreaTotal, self.cleanCountTotal, self.esimateArea = struct.unpack(">ififif", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if AppCleanInfo in parents: return 0
        tmphash = (0x6ea559d91eb65184) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if AppCleanInfo._packed_fingerprint is None:
            AppCleanInfo._packed_fingerprint = struct.pack(">Q", AppCleanInfo._get_hash_recursive([]))
        return AppCleanInfo._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", AppCleanInfo._get_packed_fingerprint())[0]

